### ISSUE TITLE
I am very interested in your work and want to cite it. Could you please provide your code?

### ISSUE THREAD

**Issue by LLMforScience** [TUM-DAML/MAGNet#1]
Hi
Thank you for your work!

I am very interested in your work and want to cite it. Could you please provide your code?

Thanks!

**Comment by johannaSommer** [comment]
Hi @AGTSAAA we are super excited to hear that you are interested in MAGNet! 🙂 I just uploaded the first version of the code. While we want to make improvements over the next few weeks (i.e. unified preprocessing, direct interface to the GuacaMol goal-directed  benchmark) I believe that this version will already be useful for you.

Let me know if you have any questions!

**Comment by LLMforScience** [comment]
Thank you very much and your work is great!

**Comment by LLMforScience** [comment]
Hi Johanna, 

Can I utilize your code  in the baseline filefold to directly run and test the baseline [HIERVAE](https://arxiv.org/pdf/2002.03230.pdf)?

Thank you very much

**Comment by johannaSommer** [comment]
Hi @AGTSAAA yes you can, this repository should include all functionality to reproduce Table 1 from the paper
