### ISSUE TITLE
The data is missing

### ISSUE THREAD

**Issue by LLMforScience** [TUM-DAML/MAGNet#5]
Hi,

Thank you for sharing the code. I want to run it but  I found the filefold `data` is empty. Could you please provide the data?

Thank you very much!

**Comment by johannaSommer** [comment]
Hi @AGTSAAA ,

yes, currently the user is expected to provide the SMILES files for a dataset themselves and preprocess them. The preprocessing files can be found in the individual `models/magnet` folders and you can find more information on the structure at `project_dir/README.md`. 

However, I am currently finalizing a version where the SMILES is downloaded and preprocessed automatically and the `project_dir` folder structure is built for you. I will have this probably by the end of this week, I hope that helps :)

**Comment by johannaSommer** [comment]
Hey @AGTSAAA as promised, main is now updated :) Please refer to the README for instructions on preprocessing
